sudo: required
language: go
go:
- tip
before_install:
  # Install the up tool chain
  - curl -sf https://up.apex.sh/install | sudo sh
  # Perform any upgrade on the up tool chain as needed
  - sudo up upgrade
script:
  # Install the go project dependencies
  - go get ./...
# deploy:
#     - provider: script
#       skip_cleanup: true
#       script: up deploy # https://beta.goserverless.sg/
#       on:
#         branch: master
#     - provider: script
#       skip_cleanup: true
#       script: up deploy production # https://goserverless.sg/
#       on:
#         tags: true
