sudo: required
language: go
go:
- tip
before_install:
  # Install the up toolchain
  - curl -sf https://up.apex.sh/install | sudo sh
  # Perform any upgrade on the up toolchain as needed
  - sudo up upgrade
script:
  # Install the go project dependencies
  - go get ./...
  # Build and run the main test case
  - go test ./...
  # Run the go build on port env PORT configured
  # and this runs in the background with the & symbol
  # (so the next step can runs)
  - go run main.go &

# deploy:
#     - provider: script
#       skip_cleanup: true
#       script: up deploy # https://beta.goserverless.sg/
#       on:
#         branch: master
#     - provider: script
#       skip_cleanup: true
#       script: up deploy production # https://goserverless.sg/
#       on:
#         tags: true
